Module4 task3
htmlacademy-adaptive/827017-cat-energy-21 pull request #10
Opened 2021-01-12 06:36 UTC by Asandra-saratov

2021-01-12 07:57 UTC, Manyaka requested changes

2021-01-12 07:57 UTC, Manyaka commented on source/less/blocks/form.less
>    font-size: 16px;
Сори, пропустила, а сейчас уже не могу оставить комент к 158 строке. Поправь там псевдоэлменты на нестинг, и афтер и бефоре

2021-01-12 07:57 UTC, Manyaka commented on source/less/blocks/gift.less
> +  margin-bottom: 35px;
марджин переопределяется, надо сразу писать как надо :)))

2021-01-12 07:58 UTC, Manyaka commented
![Screenshot 2021-01-12 at 10 52 02](https://user-images.githubusercontent.com/6417966/104285656-fd9a4080-54c4-11eb-9462-ccb84afb3acb.png)
мобила

2021-01-12 07:58 UTC, Manyaka commented
![Screenshot 2021-01-12 at 10 52 55](https://user-images.githubusercontent.com/6417966/104285732-14d92e00-54c5-11eb-9ca4-13909a8d76fb.png)
таблет

2021-01-12 07:58 UTC, Manyaka commented
![Screenshot 2021-01-12 at 10 57 04](https://user-images.githubusercontent.com/6417966/104285773-228eb380-54c5-11eb-8ef9-311c5c31cf3c.png)
десктоп

2021-01-12 07:59 UTC, Manyaka commented
![Screenshot 2021-01-12 at 10 53 42](https://user-images.githubusercontent.com/6417966/104285830-3b976480-54c5-11eb-858f-62a2075c50ed.png)
таблет

2021-01-12 08:00 UTC, Manyaka commented
![Screenshot 2021-01-12 at 10 55 54](https://user-images.githubusercontent.com/6417966/104285874-4b16ad80-54c5-11eb-94fa-138f2bc46204.png)
десктоп

2021-01-13 06:09 UTC, Manyaka requested changes

2021-01-13 06:09 UTC, Manyaka commented on source/less/blocks/form.less
> +  &:checked + .form__label {
```suggestion
  .form__input-radio {
    &:checked {
      + .form__label {
        &::after {
          display: block;
        }
      }
    }
  }
```

вот так разбей, 

кстати, а чего у тебя состояние чекед на элементе формы, тогда как оно принадлежит блоку с радио?

2021-01-13 06:09 UTC, Manyaka commented on source/less/blocks/form.less
> +  &:checked + .form__label {
аналогично для чекбокса

2021-01-13 06:11 UTC, Manyaka commented
![Screenshot 2021-01-13 at 09 07 32](https://user-images.githubusercontent.com/6417966/104413305-2979fc80-557f-11eb-95e2-b3dd66f734a7.png)
таблет
![Screenshot 2021-01-13 at 09 09 03](https://user-images.githubusercontent.com/6417966/104413330-34349180-557f-11eb-9e93-99ca99bb102a.png)
десктоп

2021-01-13 11:23 UTC, Asandra-saratov commented on source/less/blocks/form.less
> +  &:checked + .form__label {
ясно, вынесла из формы

2021-01-14 03:59 UTC, merged