PerfectPixel form
htmlacademy-adaptive/827017-cat-energy-21 pull request #12
Opened 2021-01-21 21:57 UTC by Asandra-saratov

2021-01-22 06:42 UTC, Manyaka requested changes

2021-01-22 06:43 UTC, Manyaka commented
![Screenshot 2021-01-22 at 09 00 20](https://user-images.githubusercontent.com/6417966/105456460-3e990e80-5c96-11eb-8f1d-1c12397cac45.png)

2021-01-22 06:43 UTC, Manyaka commented
![Screenshot 2021-01-22 at 09 28 07](https://user-images.githubusercontent.com/6417966/105456505-51abde80-5c96-11eb-92a3-c286266fdb84.png)

на мобилке как-то сильно расхождение

2021-01-22 06:44 UTC, Manyaka commented
![Screenshot 2021-01-22 at 09 40 57](https://user-images.githubusercontent.com/6417966/105456532-5ff9fa80-5c96-11eb-8599-36d7cc0ec3ec.png)

поработай с подчеркнутой строкой

2021-01-22 15:21 UTC, Asandra-saratov commented on source/less/global/variables.less
>  @special_grey-6: #666666;
ок, удалила

2021-01-23 06:49 UTC, Manyaka requested changes

2021-01-23 06:49 UTC, Manyaka commented on source/less/blocks/form.less
> +    &:invalid {
не так, теперь красная рамка появляется по фокусу, что противоречит стайлгайду, должна быть черная рамка же.

Держи статью: https://medium.com/russian/валидация-форм-на-html-и-css-c34c982d42a0
это перевод, тебе надо читать раздел с заголовком **Проверяем заполнено поле или нет**.

2021-01-24 05:22 UTC, merged