Module2 task1
htmlacademy-adaptive/827017-cat-energy-21 pull request #2
Opened 2020-11-15 18:53 UTC by Asandra-saratov

2020-11-16 18:51 UTC, Asandra-saratov commented on source/index.html
> +    <h1 class="visually-hidden">Cat Energy - функциональное питание для котов</h1>
Предположила так: текст "Функциональное питание для котов" больше подходит в качестве заголовка для блока, а для главного заголовка всего сайта больше подходит текст, что Cat Energy - это функциональное питание для котов. Однако инфа повторяется таким образом. Может стоит "Функциональное питание для котов" вынести в h1, а блок program назвать как "подбор программы". Тоже повторяется, но на слух получше.
Была мысль сделать в блоке program h1 "Функциональное питание для котов", но смутило: правильно ли в одном из блоков делать главный заголовок

2020-11-16 18:52 UTC, Asandra-saratov commented on source/index.html
> +        <img src="https://via.placeholder.com/100x50" alt="Логотип">
ага, ясно

2020-11-16 18:57 UTC, Asandra-saratov commented on source/index.html
> +    <main class="page-main">
да, с этим проблемка, посмотрю

2020-11-17 14:39 UTC, Asandra-saratov commented on source/index.html
> +        </div>
в <a> будет вложен svg

2020-11-17 15:08 UTC, Manyaka commented on source/index.html
> +        </div>
Щас тогда пустой свг поставь

2020-11-18 15:49 UTC, Manyaka requested changes

2020-11-18 15:49 UTC, Manyaka commented on source/index.html
> +      <img src="https://via.placeholder.com/50x50" alt="Картинка кота на логотипе «Cat Energy»">
Как правильно писать альты: https://weblind.ru и https://htmlacademy.ru/blog/boost/frontend/alt-text

Оттуда цитата: 

> Не начинайте со слов «картинка» или «изображение».

Также, я чето первый раз забыла сказать, что и в альтах надо ставить точки, чтобы скрин-ридер делал на них паузу.

2020-11-18 15:49 UTC, Manyaka commented on source/index.html
> +      <img src="https://via.placeholder.com/50x50" alt="Картинка кота на логотипе «Cat Energy»">
Точки везде поставь, я не буду писать дублирующие комменты

2020-11-18 15:49 UTC, Manyaka commented on source/index.html
> +      <img src="https://via.placeholder.com/50x50" alt="Картинка кота на логотипе «Cat Energy»">
Ну и везде слова про картинку тоже поубирай, тоже не буду дублироваться

2020-11-18 15:49 UTC, Manyaka commented on source/index.html
> +      <div class="link-to-catalog-list__wrapper">
`link-to-catalog-list__wrapper` - это название элемента, элементы не могут быть без блоков, но в любом случае подумай, серый див это блок или элемент catalog-selectionа?

2020-11-19 15:33 UTC, merged