Module2 task2
htmlacademy-adaptive/827017-cat-energy-21 pull request #3
Opened 2020-11-18 20:46 UTC by Asandra-saratov

2020-11-19 07:53 UTC, Manyaka requested changes

2020-11-19 07:53 UTC, Manyaka commented on source/index.html
>  <!DOCTYPE html>
Верни как было, иначе будут конфликты при ребейзе. Мы их конечно порешаем, но для начала, пусть будет без конфликтов.

2020-11-19 07:53 UTC, Manyaka commented on source/form.html
> +          <a href="form.html">
Мы находимся на этой странице, поэтому уже не надо человека куда-то направлять:
```suggestion
          <a>
```

2020-11-19 07:53 UTC, Manyaka commented on source/form.html
> +    <section class="form">
Нет, класс `form` принадлежит форме, потому что это она тот независимый блок по бему, который мы можем куда-то перенести.

2020-11-19 07:53 UTC, Manyaka commented on source/form.html
> +        <input class="button" type="submit" value="Отправить заявку">
Используй тег `button`. Инпут тип сабмит уже не используется, чтобы делать кнопки отправки форм

2020-11-19 07:53 UTC, Manyaka commented on source/form.html
> +      <p class="form__note form__note--required">- Обязательные поля</p>
Звездочку будешь псевдоэлементом делать?

2020-11-19 07:53 UTC, Manyaka commented on source/form.html
> +              <input class="form__field" type="text" name="cat-name" id="weight-id" placeholder="7" required>
```suggestion
              <input class="form__field" type="number" name="cat-weight" id="weight-id" placeholder="7" required>
```

2020-11-19 07:53 UTC, Manyaka commented on source/form.html
> +              <input class="form__field" type="text" name="cat-name" id="age-id" placeholder="7">
```suggestion
              <input class="form__field" type="number" name="cat-age" id="age-id" placeholder="7">
```

2020-11-19 07:53 UTC, Manyaka commented on source/form.html
> +              <input class="form__item--radio" type="radio" name="choice" id="choice-slimming-id"
https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80-%D0%BD%D0%B5%D0%BB%D1%8C%D0%B7%D1%8F-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%81%D0%B0%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE

если по якорю не отркроет нужный раздел, то мотай до Принципы работы с модификаторами и Модификатор нельзя использовать самостоятельно

2020-11-19 07:53 UTC, Manyaka commented on source/form.html
> +          <legend class="form__subtitle subtitle">Контактные данные (владельца кота)</legend>
Зачем из этого заголовка делать самостоятельный блок?

2020-11-19 07:53 UTC, Manyaka commented on source/form.html
> +              <label class="form__label form__field--required" for="cat-name-id">Имя:</label>
```suggestion
              <label class="form__label form__label--required" for="cat-name-id">Имя:</label>
```
Почитай ещё раз про модификаторы

2020-11-19 07:53 UTC, Manyaka commented on source/form.html
> +              <label class="form__label form__field--required" for="cat-name-id">Имя:</label>
поправить все вхождения

2020-11-19 07:53 UTC, Manyaka commented on source/form.html
> +              <input class="form__field form__field--icon-phone" type="text" name="phone" id="phone-id"
Почитай какие бывают типы инпутов: http://htmlbook.ru/html/input/type и подставь соотв

2020-11-19 07:53 UTC, Manyaka commented on source/form.html
> +          <textarea class="form__field" name="comment" id="comment-id"
Добавь скрытый лебл для доступности

2020-11-19 08:31 UTC, Asandra-saratov commented on source/form.html
> +      <p class="form__note form__note--required">- Обязательные поля</p>
да

2020-11-21 16:01 UTC, Asandra-saratov commented on source/form.html
> +          <legend class="form__subtitle subtitle">Контактные данные (владельца кота)</legend>
Была мысль сделать один класс для оформления таких заголовков с зеленой полосой в форме и каталоге

2020-11-21 17:04 UTC, Manyaka commented on source/form.html
> +          <legend class="form__subtitle subtitle">Контактные данные (владельца кота)</legend>
Да, так можно. Оставляй тогда

2020-11-23 05:33 UTC, Manyaka requested changes

2020-11-23 05:33 UTC, Manyaka commented on source/form.html
> +        <p class="form-container__note form-container__note--required">- Обязательные поля</p>
Параграф находится внутри блока `.form`, и имеет смысл для этого блока, и с ним его можно переносить, так что это элемент блока `.form`

2020-11-23 08:34 UTC, Manyaka requested changes

2020-11-23 08:34 UTC, Manyaka commented on source/form.html
> +        <p class="form__note form__note--required">- Обязательные поля</p>
Ему не нужен мод, он сам по себе такой со звездочкой параграф

2020-11-23 08:51 UTC, merged