Module3 task1
htmlacademy-adaptive/827017-cat-energy-21 pull request #5
Opened 2020-11-30 20:38 UTC by Asandra-saratov

2020-12-01 08:23 UTC, Manyaka requested changes

2020-12-01 08:23 UTC, Manyaka commented on source/less/style.less
> +// Global
Предлагаю сортировать их по алфавиту

2020-12-01 08:23 UTC, Manyaka commented on source/less/global/global.less
> +}
https://up.htmlacademy.ru/adaptive/21/criteries#d16

> Нет глобальных стилей тегов.

2020-12-01 08:23 UTC, Manyaka commented on source/less/global/fonts.less
> +@arial: "Arial";
Переменные хранятся в соотв. файле

2020-12-01 08:23 UTC, Manyaka commented on source/less/blocks/button.less
> +  font-family: "Oswald", "Arial", sans-serif;
добавь шрифты для мака и линукса, расположи их в правильном порядке

https://up.htmlacademy.ru/adaptive/21/criteries#b10

> Указаны альтернативные варианты шрифта

2020-12-01 08:23 UTC, Manyaka commented on source/less/blocks/catalog-selection.less
> +.link-to-catalog-list {
https://up.htmlacademy.ru/adaptive/21/criteries#b13

> Для каждого БЭМ-блока нужно создать отдельный файл стилей.

2020-12-01 08:23 UTC, Manyaka commented on source/less/blocks/page-footer.less
> +.copyright__link {
Для каждого БЭМ-блока нужно создать отдельный файл стилей.

2020-12-01 08:23 UTC, Manyaka commented on source/less/blocks/page-footer.less
> +.social__item {
Для каждого БЭМ-блока нужно создать отдельный файл стилей.

2020-12-01 08:23 UTC, Manyaka commented on source/less/blocks/page-header.less
> +.main-nav__list-item,
Для каждого БЭМ-блока нужно создать отдельный файл стилей.

2020-12-01 08:23 UTC, Manyaka commented on source/less/blocks/page-header.less
> +.main-nav__list-item,
поправь все остальные случаи

2020-12-01 08:24 UTC, Manyaka commented
![Screenshot 2020-12-01 at 11 18 21](https://user-images.githubusercontent.com/6417966/100715043-b1d58100-33c7-11eb-97ab-d160048fbe99.png)

2020-12-01 08:24 UTC, Manyaka commented
![Screenshot 2020-12-01 at 11 14 01](https://user-images.githubusercontent.com/6417966/100715091-bf8b0680-33c7-11eb-97bd-39d744b31ff6.png)

2020-12-01 08:24 UTC, Manyaka commented
![Screenshot 2020-12-01 at 11 00 55](https://user-images.githubusercontent.com/6417966/100715145-d0d41300-33c7-11eb-8320-08f2799d45b1.png)

2020-12-02 08:17 UTC, Manyaka requested changes

2020-12-02 18:54 UTC, Asandra-saratov commented on source/index.html
> +      <img src="../img/logo-cat-mobile.svg" alt="Кот на логотипе «Cat Energy».">
странная штука, у меня так отображается
![image](https://user-images.githubusercontent.com/64925856/100917821-1b04e380-34f1-11eb-9644-2f4736293141.png)
https://github.com/htmlacademy-adaptive/827017-cat-energy-21/blob/272b494b5accd0d0cd6e6fd5f6bf998e558cf13d/source/index.html

2020-12-05 08:33 UTC, merged