Module4 task2
htmlacademy-adaptive/827017-cat-energy-21 pull request #9
Opened 2021-01-07 23:03 UTC by Asandra-saratov

2021-01-08 06:16 UTC, Manyaka requested changes

2021-01-08 06:16 UTC, Manyaka commented on source/form.html
> +        <li class="main-nav__list-item main-nav__list-item--color">
Для чего ты используешь этот модификатор `main-nav__list-item--color`? Удобнее его вынести на уровень списка, чтобы не дублировать, а еще удобнее добавить этот модификатор тем элементам, которые отличаются от дефолтного чёрного цвета: те не в форму и каталог добавлять мод, а на главную его добавить

2021-01-08 06:16 UTC, Manyaka commented on source/form.html
> +                <input class="form__input-radio visually-hidden form__input-radio--radio-button" type="radio"
Зачем тут мод `form__input-radio--radio-button`? Можно ли обойтись элементом `form__input-radio`?

2021-01-08 06:16 UTC, Manyaka commented on source/form.html
> +              <input class="form__input-checkbox visually-hidden form__input-checkbox--checkbox-field" type="checkbox"
Аналогично, тут функцию мода `form__input-checkbox--checkbox-field` можно перенести на элемент `form__input-checkbox?`

2021-01-08 06:16 UTC, Manyaka commented on source/form.html
> +    <section class="map map--color">
Тут тоже, модификатор надо делать к элементу, который отличается от других, `map--color` - это у тебя серый бг, серый бг встречается 2 раза, тогда как белый - 1 раз. Значит модификатор нужен белому бг.

Но в твоем случае ещё проще: серый бг у мобилы и таблета, а белый у деска, значит можно вообще обойтись без модификатора и использовать медиа квери на деск, чтобы покрасить бг в белый.

2021-01-08 06:16 UTC, Manyaka commented on source/less/blocks/form.less
> +  &--radio-button::before {
все псевдоэлементы делай через парент селектор, как у тебя везде по коду

2021-01-09 16:59 UTC, Asandra-saratov commented on source/form.html
> +              <input class="form__input-checkbox visually-hidden form__input-checkbox--checkbox-field" type="checkbox"
да, лишний, переделала

2021-01-09 17:15 UTC, Asandra-saratov commented on source/form.html
> +    <section class="map map--color">
оставила map--color для главной стр

2021-01-10 10:02 UTC, Manyaka requested changes

2021-01-10 15:02 UTC, merged